using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CloudController : MonoBehaviour
{
    //Å‘åƒTƒCƒY
    private float minimum = 1.0f;
    //Šg‘åk¬ƒXƒs[ƒh
    private float magSpeed = 10.0f;
    //Šg‘å—¦
    private float magnification = 0.07f;
    void Start()
    {
        
    }

    void Update()
    {
        //‰_‚ğŠg‘åk¬
        this.transform.localScale = new Vector3(this.minimum + Mathf.Sin(Time.time* this.magSpeed) * this.magnification, this.transform.localScale.y, this.minimum + Mathf.Sin(Time.time * this.magSpeed) * this.magnification);
    }
}
